ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS weight numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS height numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS width numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS length numeric NOT NULL DEFAULT 0;